In [3]:
import tensorflow as tf
import numpy as np
import time
import os

2021-12-02 11:35:01.113685: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


In [2]:
FILE_DIR = '/home/jsryu1228/crawling/temp'

In [42]:
class FileDataset(tf.data.Dataset):
    def read_files_in_batches(num_samples):
        #time.sleep(0.03)
        for sample_idx in range(num_samples):
            #time.sleep(0.015)
            yield (sample_idx,)
            
    def __new__(cls, num_samples=3):
        # FileDataset이 생성되면 새로 호출
        return tf.data.Dataset.from_generator(
            cls.read_files_in_batches,
            output_signature=tf.TensorSpec(shape=(1,), dtype=tf.int64),
            args=(num_samples, )   
        )

In [44]:
def train(dataset, num_epochs=2):
    for epoch_num in range(num_epochs):
        for sample in dataset:
            print(sample)
            #time.sleep(0.01)

In [45]:
%%timeit
train(FileDataset())

tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)


tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)


tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([0], shape=(1,), dtype=int64)


In [22]:
%%timeit
train(FileDataset().prefetch(1))

225 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
%%timeit
train(FileDataset().prefetch(tf.data.AUTOTUNE))

226 ms ± 2.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
dataset = tf.data.Dataset.range(15)
for d in dataset:
    print(d.numpy())

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [29]:
dataset = dataset.map(lambda x:x**2 + 1)

for d in dataset:
    print(d.numpy())

1
2
17
82
257
626
1297
2402
4097
6562
10001
14642
20737
28562
38417


In [30]:
dataset = dataset.cache()

for d in dataset.as_numpy_iterator():
    print(d)

1
2
17
82
257
626
1297
2402
4097
6562
10001
14642
20737
28562
38417


In [31]:
list(dataset.as_numpy_iterator())

[1,
 2,
 17,
 82,
 257,
 626,
 1297,
 2402,
 4097,
 6562,
 10001,
 14642,
 20737,
 28562,
 38417]

In [33]:
def mapped_function(s):
    tf.py_function(lambda: time.sleep(0.03), [], ())
    return s

In [37]:
%%timeit -n1 -r1
train(FileDataset().map(mapped_function),5)

1.12 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [38]:
%%timeit -n1 -r1
train(FileDataset().map(mapped_function).cache(),5)

395 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
